name = "botpad-api"
main = "worker.js"
compatibility_date = "2024-12-01"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "RECREATE"
id = "c83fc2b6029d4a8a8acff8c3de19ac03"

[[d1_databases]]
binding = "DB"
database_name = "codeagentgbt"
database_id = "028ee745-d504-403f-8bee-87ac220c9b59"
